apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejemplo-tini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejemplo-tini
  template:
    metadata:
      labels:
        app: ejemplo-tini
    spec:
      containers:
      - name: ejemplo-tini
        image: tu-imagen-con-tini:latest
        args: ["your-application"]
