apiVersion: v1
kind: Pod
metadata:
 name: non-root-ubuntu
spec:
 containers:
   - name: test
     image: ubuntu:latest
     securityContext:
       runAsUser: 1000
       runAsGroup: 1000
     command: [ "sleep", "infinity" ]


# https://snyk.io/blog/kernel-privilege-escalation/