apiVersion: v1
kind: Pod 
metadata:
  name: cpu-demo2
spec:
  containers:
  - name: cpudemo-ctr
    image: vish/stress
    args:
    - -cpus
    - "100"
    resources:
      limits:
        cpu: "1000m"
      requests:
        cpu: "500m"
