apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s-hands-on
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: k8s-hands-on
          # image: k8s-hands-on
          image: frontend-k8s-hands-on:v1
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-hands-on
  labels: 
    app: frontend
spec:
  # type: NodePort  # Desde el navegador
  # type: ClusterIP  # Desde dentro del cluster
  # selector:
  #   app: frontend
  # ports:
  #   - protocol: TCP
  #     port: 80
  #     targetPort: 9090  # que puerto dentro del contenedor o del pod voy a consumir

# Para poder ver la conexion con la API de go dedel browser.
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 80  
      targetPort: 80 # Puerto que se ejecuta en el pod en el 80
      protocol: TCP

