apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-service
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels: 
    app: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80  # que puerto dentro del contneedor o del pod voy a consumir
